backend:

  name: github
  repo: dafa00/sisa-kebahagiaan # Path to Github repository
  branch: gh-pages # Branch to update


# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "img" # Media files will be stored in the repo under images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images

collections:

 - name: "page"
   label: "Components"
   folder: "components"
   sort: "title:asc"
   create: true
   slug: "{{slug}}"
   fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Type", name: "type", widget: "hidden", default: "components" }
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown" }

 - name: "page"
   label: "Foundations"
   folder: "foundations"
   sort: "title:asc"
   create: true
   slug: "{{slug}}"
   fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Type", name: "type", widget: "hidden", default: "components" }
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown" }
